name: PR

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target lint -t problem-solving-lint -f docker/Dockerfile .
      - run: docker run problem-solving-lint

  coding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target coding -t problem-solving-coding -f docker/Dockerfile .
      - run: docker run problem-solving-coding
